#pragma once
#ifndef CATA_SRC_COMPUTER_ENUMS_H
#define CATA_SRC_COMPUTER_ENUMS_H

#include "enum_traits.h"

enum computer_action {
    COMPACT_NULL = 0,
    COMPACT_AMIGARA_LOG,
    COMPACT_AMIGARA_START,
    COMPACT_BLOOD_ANAL,
    COMPACT_CASCADE,
    COMPACT_COMPLETE_DISABLE_EXTERNAL_POWER, // Completes "Disable External Power" mission
    COMPACT_CONVEYOR,
    COMPACT_DATA_ANAL,
    COMPACT_DEACTIVATE_SHOCK_VENT,
    COMPACT_DISCONNECT,
    COMPACT_DOWNLOAD_SOFTWARE,
    COMPACT_ELEVATOR_ON,
    COMPACT_EMERG_MESS,
    COMPACT_EMERG_REF_CENTER,   //Points to the refugee center
    COMPACT_EXTRACT_RAD_SOURCE,
    COMPACT_GEIGER,
    COMPACT_IRRADIATOR,
    COMPACT_LIST_BIONICS,
    COMPACT_LIST_MUTATIONS,
    COMPACT_LOCK,
    COMPACT_MAP_SEWER,
    COMPACT_MAP_SUBWAY,
    COMPACT_MAPS,
    COMPACT_MISS_DISARM,
    COMPACT_MISS_LAUNCH,
    COMPACT_OPEN,
    COMPACT_OPEN_DISARM,
    COMPACT_OPEN_GATE,
    COMPACT_CLOSE_GATE,
    COMPACT_PORTAL,
    COMPACT_RADIO_ARCHIVE,
    COMPACT_RELEASE,
    COMPACT_RELEASE_BIONICS,
    COMPACT_RELEASE_DISARM,
    COMPACT_REPEATER_MOD,       //Converts a terminal in a radio station into a 'repeater', locks terminal and completes mission
    COMPACT_RESEARCH,
    COMPACT_SAMPLE,
    COMPACT_SHUTTERS,
    COMPACT_SR1_MESS,           //Security Reminders for Hazardous Waste Sarcophagus (SRCF)
    COMPACT_SR2_MESS,
    COMPACT_SR3_MESS,
    COMPACT_SR4_MESS,
    COMPACT_SRCF_1_MESS,
    COMPACT_SRCF_2_MESS,
    COMPACT_SRCF_3_MESS,
    COMPACT_SRCF_ELEVATOR,
    COMPACT_SRCF_SEAL,
    COMPACT_SRCF_SEAL_ORDER,
    COMPACT_TERMINATE,
    COMPACT_TOLL,
    COMPACT_TOWER_UNRESPONSIVE,
    COMPACT_UNLOCK,
    COMPACT_UNLOCK_DISARM,
    NUM_COMPUTER_ACTIONS
};

enum computer_failure_type {
    COMPFAIL_NULL = 0,
    COMPFAIL_ALARM,
    COMPFAIL_AMIGARA,
    COMPFAIL_DAMAGE,
    COMPFAIL_DESTROY_BLOOD,
    COMPFAIL_DESTROY_DATA,
    COMPFAIL_MANHACKS,
    COMPFAIL_PUMP_EXPLODE,
    COMPFAIL_PUMP_LEAK,
    COMPFAIL_SECUBOTS,
    COMPFAIL_SHUTDOWN,
    NUM_COMPUTER_FAILURES
};

template<>
struct enum_traits<computer_action> {
    static constexpr computer_action last = NUM_COMPUTER_ACTIONS;
};

template<>
struct enum_traits<computer_failure_type> {
    static constexpr computer_failure_type last = NUM_COMPUTER_FAILURES;
};

#endif // CATA_SRC_COMPUTER_ENUMS_H
